# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4cf74e8880ebe6644151519ccd6e436861006c8866752006846fca55d13922d42f73db74ad040ac707ebf1009d39004b668c20669b15075d834167d714edcff

test:
  secret_key_base: 033d7f642ac3f07512f0fa3a42ade239920b07eea1d77ea19c036c2957e9c7a1390e6e41ccf6524c6869c1bf2113e0923492dbf0bab7f891d6dbfb6373dc02f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
